<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var backend\models\DataDiri $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="box box-info">
    <div class="box-body">
        <?php $form = ActiveForm::begin([
        'id' => 'DataDiri',
        'layout' => 'horizontal',
        'enableClientValidation' => true,
        'errorSummaryCssClass' => 'error-summary alert alert-error'
        ]
        );
        ?>
        
			<?= $form->field($model, 'id')->textInput() ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'id_user')->dropDownList(
    \yii\helpers\ArrayHelper::map(backend\models\User::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['id_user'])),
    ]
); ?>
			<?= $form->field($model, 'nama_lengkap')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'nama_panggilan')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'foto')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'tempat_lahir')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'alamat_tinggal')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'no_hp')->textInput() ?>
			<?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'akun_fb')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'akun_ig')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'akun_li')->textInput(['maxlength' => true]) ?>        <hr/>
        <?php echo $form->errorSummary($model); ?>
        <div class="row">
            <div class="col-md-offset-3 col-md-10">
                <?=  Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']); ?>
                <?=  Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['index'], ['class' => 'btn btn-default']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>

    </div>
</div>