<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;

/**
 * @var yii\web\View $this
 * @var backend\models\Akademik $model
 * @var yii\widgets\ActiveForm $form
 */

?>

<div class="box box-info">
    <div class="box-body">
        <?php $form = ActiveForm::begin([
                'id' => 'Akademik',
                'layout' => 'horizontal',
                'enableClientValidation' => true,
                'errorSummaryCssClass' => 'error-summary alert alert-error'
            ]
        );
        ?>
        <?php if (Yii::$app->user->identity->type == 2) {
            echo $form->field($model, 'nim')->textInput(['value' => Yii::$app->user->identity->nim, 'readonly' => true]);
        } else {
            echo $form->field($model, 'nim')->widget(\kartik\select2\Select2::className(), [
                'data' => \yii\helpers\ArrayHelper::map(backend\models\User::find()->all(), 'nim', 'nim'),
                'language' => 'id',
                'options' => ['placeholder' => 'Pilih NIM ...'],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]);
        } ?>
        <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
        $form->field($model, 'jurusan')->widget(\kartik\select2\Select2::className(), [
            'data' => \yii\helpers\ArrayHelper::map(backend\models\MasterJurusan::find()->all(), 'id', 'nama_jurusan'),
            'language' => 'id',
            'options' => ['placeholder' => 'Pilih Jurusan ...'],
            'pluginOptions' => [
                'allowClear' => true
            ],
        ]);
        ?>
        <?= $form->field($model, 'batch')->textInput() ?>
        <hr/>
        <?php echo $form->errorSummary($model); ?>
        <div class="row">
            <div class="col-md-offset-3 col-md-10">
                <?= Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']); ?>
                <?= Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['index'], ['class' => 'btn btn-default']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>

    </div>
</div>