<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;

/**
 * @var yii\web\View $this
 * @var backend\models\Berita $model
 * @var yii\widgets\ActiveForm $form
 */

?>

<div class="box box-info">
    <div class="box-body">
        <?php $form = ActiveForm::begin([
                'id' => 'Berita',
                'layout' => 'horizontal',
                'enableClientValidation' => false,
                'errorSummaryCssClass' => 'error-summary alert alert-error',
                'options' => ['enctype' => 'multipart/form-data'],
            ]
        );
        ?>

        <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
        $form->field($model, 'id_kategori')->widget(\kartik\select2\Select2::className(), [
            'data' =>  \yii\helpers\ArrayHelper::map(backend\models\Kategori::find()->all(), 'id', 'nama_kategori'),
            'language' => 'id',
            'options' => ['placeholder' => 'Pilih Kategori ...'],
            'pluginOptions' => [
                'allowClear' => true
            ],
        ]);?>
        <?= $form->field($model, 'judul')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'isi_berita')->widget(\dosamigos\tinymce\TinyMce::className(), [
            'options' => ['rows' => 6],
            'language' => 'id',
            'clientOptions' => [
                'plugins' => [
                    "advlist autolink lists link charmap print preview anchor",
                    "searchreplace visualblocks code fullscreen",
                    "insertdatetime media table contextmenu paste"
                ],
                'toolbar' => "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
            ]
        ]);?>
        <?= $form->field($model, 'foto')->widget(\kartik\file\FileInput::className(), [
            'options' => ['accept' => 'image/*'],
            'pluginOptions' => [
                'allowedFileExtensions' => ['jpg', 'png', 'jpeg', 'gif', 'bmp'],
                'maxFileSize' => 250,
            ],
        ]) ?>
        <?php
        if ($model->foto != null){
            ?>
            <div class="form-group">
                <div class="col-sm-6 col-sm-offset-3">
                    <img src="<?= Yii::$app->urlManagerFotoBerita->baseUrl.'/'.$model->foto?>">
                    </div>
            </div>
        <?php } ?>
        <?= $form->field($model, 'tanggal')->textInput(['value' => date('Y-m-d'), 'readonly' => true]) ?>
        <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
        $form->field($model, 'id_user')->hiddenInput(['value'=> Yii::$app->user->identity->id])->label(false) ?>
        <hr/>
        <?php echo $form->errorSummary($model); ?>
        <div class="row">
            <div class="col-md-offset-3 col-md-10">
                <?= Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']); ?>
                <?= Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['index'], ['class' => 'btn btn-default']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>

    </div>
</div>