<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
$this->title = 'Data Perusahaan';
?>
<?php \yii\widgets\Pjax::begin(['id' => 'pjax-main', 'enableReplaceState' => false, 'linkSelector' => '#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>
<section class=" page_indicator">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 text-right page_indicator_text">
                <a href="<?= Yii::$app->request->baseUrl ?>">Home </a><i class="fa fa-long-arrow-right"
                                                                         aria-hidden="true"></i><span
                    class="text-primary">Data Perusahaan</span>
            </div>
        </div>
    </div>
</section>
<div class="container styles" id="typography">
    <div class="row">
        <div class="row">
            <div class="col-xs-12">
                <h3 class="text-center">
                    Data <span class="header_help">Perusa</span>haan
                </h3>
            </div>
        </div>
        <div class="row styles_table wow fadeInLeft" data-wow-duration="1s" data-wow-delay="0.2s">
            <div class="col-md-12 section-top-15">
                <h3><span class="header_help">List Perusahaan</h3>

            </div>
            <div class="col-md-12 section-top-15">
                <div class="table-responsive">
                    <?= GridView::widget([
                        'layout' => '{summary}{pager}{items}{pager}',
                        'dataProvider' => $dataProvider,
                        'pager' => [
                            'class' => yii\widgets\LinkPager::className(),
                            'firstPageLabel' => Yii::t('cruds', 'First'),
                            'lastPageLabel' => Yii::t('cruds', 'Last')],
                        'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
                        'headerRowOptions' => ['class' => 'x'],
                        'columns' => [

                            //\app\components\ActionButton::getButtons(),

                            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
                            'nama_perusahaan',
                            [
                                'class' => yii\grid\DataColumn::className(),
                                'attribute' => 'id_usaha',
                                'value' => function ($model) {
                                    if ($rel = $model->getIdUsaha()->one()) {
                                        return $rel->nama_usaha;
                                    } else {
                                        return '';
                                    }
                                },
                                'format' => 'raw',
                            ],
                            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
                            [
                                'class' => yii\grid\DataColumn::className(),
                                'attribute' => 'id_bisnis',
                                'value' => function ($model) {
                                    if ($rel = $model->getIdBisnis()->one()) {
                                        return $rel->nama_tahapan_bisnis;
                                    } else {
                                        return '';
                                    }
                                },
                                'format' => 'raw',
                            ],
                            'tahun_berdiri',
                            'alamat_perusahaan',
                            'no_telp_kantor',
                            'email_kantor',
                        ],
                    ]); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php \yii\widgets\Pjax::end() ?>