<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\controllers\base;

use backend\models\Tentang;
use backend\models\TentangSearch;
use yii\web\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;

/**
 * TentangController implements the CRUD actions for Tentang model.
 */
class TentangController extends Controller
{


    /**
     * @var boolean whether to enable CSRF validation for the actions in this controller.
     * CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
     */
    public $enableCsrfValidation = false;


    /**
     * Lists all Tentang models.
     * @return mixed
     */
    public function actionIndex()
    {
        $model = Tentang::find()->where(['id' => 1])->one();

        if ($model->load($_POST) && $model->save()) {
            \Yii::$app->session->addFlash("success", "Tentang Kami successfully updated.");
        }
        return $this->render('index', [
            'model' => $model,
        ]);
    }

}
