<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;

/**
 * @var yii\web\View $this
 * @var backend\models\PerusahaanSatu $model
 * @var yii\widgets\ActiveForm $form
 */

?>

<div class="box box-info">
    <div class="box-body">
        <?php $form = ActiveForm::begin([
                'id' => 'PerusahaanSatu',
                'layout' => 'horizontal',
                'enableClientValidation' => false,
                'errorSummaryCssClass' => 'error-summary alert alert-error',
                'options' => ['enctype' => 'multipart/form-data'],
            ]
        );
        ?>

        <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
        $form->field($model, 'id_usaha')->widget(\kartik\select2\Select2::className(), [
            'data' =>  \yii\helpers\ArrayHelper::map(backend\models\Usaha::find()->all(), 'id', 'nama_usaha'),
            'language' => 'id',
            'options' => ['placeholder' => 'Pilih Usaha ...'],
            'pluginOptions' => [
                'allowClear' => true
            ],
        ]);
        ?>
        <?=   $form->field($model, 'id_bisnis')->widget(\kartik\select2\Select2::className(),[
            'data' =>  \yii\helpers\ArrayHelper::map(backend\models\Bisnis::find()->all(), 'id', 'nama_tahapan_bisnis'),
            'language' => 'id',
            'options' => ['placeholder' => 'Pilih Tahapan Bisnis ...'],
            'pluginOptions' => [
                'allowClear' => true
            ],
        ])?>
        <?= $form->field($model, 'nama_perusahaan')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'logo_perusahaan')->widget(\kartik\file\FileInput::className(), [
            'options' => ['accept' => 'image/*'],
            'pluginOptions' => [
                'allowedFileExtensions' => ['jpg', 'png', 'jpeg', 'gif', 'bmp'],
                'maxFileSize' => 250,
            ],
        ]) ?>
        <?php
        if ($model->logo_perusahaan != null){
        ?>

        <div class="form-group">
            <div class="col-sm-6 col-sm-offset-3">
                <?= Html::img(["uploads/perusahaan_st/" . $model->logo_perusahaan], ["width" => "150px"]); ?>
            </div>
        </div>
        <?php } ?>
        <?= $form->field($model, 'tahun_berdiri')->widget(\yii\widgets\MaskedInput::className(),[
            'name' => 'input-37',
            'mask' => 'j', // basic year
            'definitions' => ['j' => [
                'validator' => '[0-9\(\)\.\+/ ]',
                'cardinality' => 4,
                'prevalidator' =>  [
                    ['validator' => '[12]', 'cardinality' => 1],
                    ['validator' => '(19|20)', 'cardinality' => 2],
                    ['validator' => '(19|20)\\d', 'cardinality' => 3],
                ]
            ]]
        ]) ?>
        <?= $form->field($model, 'alamat_perusahaan')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'no_telp_kantor')->widget(\yii\widgets\MaskedInput::className(),[
            'name' => 'input-3',
            'mask' => '9',
            'clientOptions' => ['repeat' => 15, 'greedy' => false]
        ]) ?>
        <?= $form->field($model, 'email_kantor')->widget(\yii\widgets\MaskedInput::className(),[
            'name' => 'input-36',
            'clientOptions' => [
                'alias' =>  'email'
            ],
        ]) ?>
        <?= $form->field($model, 'deskripsi_singkat')->textarea(['rows' => 6]) ?>
        <?= $form->field($model, 'deskripsi_panjang')->textarea(['rows' => 6]) ?>
        <?= $form->field($model, 'portofolio_perusahaan')->widget(\kartik\file\FileInput::className(), [
            'options' => ['accept' => 'image/*'],
            'pluginOptions' => [
                'allowedFileExtensions' => ['jpg', 'png', 'jpeg', 'gif', 'bmp'],
                'maxFileSize' => 250,
            ],
        ]) ?>
        <?php
        if ($model->portofolio_perusahaan != null){
            ?>

            <div class="form-group">
                <div class="col-sm-6 col-sm-offset-3">
                    <?= Html::img(["uploads/perusahaan_st/" . $model->portofolio_perusahaan], ["width" => "150px"]); ?>
                </div>
            </div>
        <?php } ?>
        <?= $form->field($model, 'foto_dokumentasi')->widget(\kartik\file\FileInput::className(), [
            'options' => ['accept' => 'image/*'],
            'pluginOptions' => [
                'allowedFileExtensions' => ['jpg', 'png', 'jpeg', 'gif', 'bmp'],
                'maxFileSize' => 250,
            ],
        ]) ?>
        <?php
        if ($model->foto_dokumentasi != null){
            ?>

            <div class="form-group">
                <div class="col-sm-6 col-sm-offset-3">
                    <?= Html::img(["uploads/perusahaan_st/" . $model->foto_dokumentasi], ["width" => "150px"]); ?>
                </div>
            </div>
        <?php } ?>
        <?= $form->field($model, 'upload_company_profile')->widget(\kartik\file\FileInput::className(), [
            'options' => ['accept' => 'pdf/*'],
            'pluginOptions' => [
                'allowedFileExtensions' => ['pdf'],
                'maxFileSize' => 250,
            ],
        ]) ?>
        <?php
        if ($model->upload_company_profile != null){
            ?>

            <div class="form-group">
                <div class="col-sm-6 col-sm-offset-3">
                    <?= Html::img(["uploads/perusahaan_st/" . $model->upload_company_profile], ["width" => "150px"]); ?>
                </div>
            </div>
        <?php } ?>
        <?php if (Yii::$app->user->identity->type == 2) {
            echo $form->field($model, 'id_user')->hiddenInput(['value' => Yii::$app->user->identity->id])->label(FALSE);
        } else {
           echo $form->field($model, 'id_user')->widget(\kartik\select2\Select2::className(), [
                'data' => \yii\helpers\ArrayHelper::map(backend\models\User::find()->where(['type' => 2])->all(), 'id', 'nim'),
                'language' => 'id',
                'options' => ['placeholder' => 'Pilih NIM member ...'],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ])->label('Member');
        }
        ?>
        <hr/>
        <?php echo $form->errorSummary($model); ?>
        <div class="row">
            <div class="col-md-offset-3 col-md-10">
                <?= Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']); ?>
                <?= Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['index'], ['class' => 'btn btn-default']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>

    </div>
</div>