<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var backend\models\PerusahaanSatuSearch $searchModel
 */

$this->title = Yii::t('cruds', 'Data Perusahaan');
$this->params['breadcrumbs'][] = $this->title;
?>

<p>

    <?php
    if (Yii::$app->user->identity->type == 2) {
        if ($cek >= 4) {
            echo "";
        } else {
            echo Html::a('<i class="fa fa-plus"></i> Tambah Baru', ['create'], ['class' => 'btn btn-success']);
        };
    } else {
        echo Html::a('<i class="fa fa-plus"></i> Tambah Baru', ['create'], ['class' => 'btn btn-success']);
    }
    ?>
</p>


<?php \yii\widgets\Pjax::begin(['id' => 'pjax-main', 'enableReplaceState' => false, 'linkSelector' => '#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>

<div class="box box-info">
    <div class="box-body">
        <div class="table-responsive">
            <?= GridView::widget([
                'layout' => '{summary}{pager}{items}{pager}',
                'dataProvider' => $dataProvider,
                'pager' => [
                    'class' => yii\widgets\LinkPager::className(),
                    'firstPageLabel' => Yii::t('cruds', 'First'),
                    'lastPageLabel' => Yii::t('cruds', 'Last')],
                'filterModel' => $searchModel,
                'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
                'headerRowOptions' => ['class' => 'x'],
                'columns' => [

                    \app\components\ActionButton::getButtons(),

                    // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
                    'nama_perusahaan',
                    [
                        'class' => yii\grid\DataColumn::className(),
                        'attribute' => 'id_usaha',
                        'value' => function ($model) {
                            if ($rel = $model->getIdUsaha()->one()) {
                                return $rel->nama_usaha;
                            } else {
                                return '';
                            }
                        },
                        'format' => 'raw',
                    ],
                    // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
                    [
                        'class' => yii\grid\DataColumn::className(),
                        'attribute' => 'id_bisnis',
                        'value' => function ($model) {
                            if ($rel = $model->getIdBisnis()->one()) {
                                return $rel->nama_tahapan_bisnis;
                            } else {
                                return '';
                            }
                        },
                        'format' => 'raw',
                    ],
                    'tahun_berdiri',
                    'alamat_perusahaan',
                    'no_telp_kantor',
                    /*'email_kantor:email'*/
                    /*'deskripsi_singkat:ntext'*/
                    /*'deskripsi_panjang:ntext'*/
                    /*'portofolio_perusahaan'*/
                    /*'foto_dokumentasi'*/
                    /*'upload_company_profile'*/
                    /*// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
        [
            'class' => yii\grid\DataColumn::className(),
            'attribute' => 'id_user',
            'value' => function ($model) {
                if ($rel = $model->getIdUser()->one()) {
                    return Html::a($rel->id, ['user/view', 'id' => $rel->id,], ['data-pjax' => 0]);
                } else {
                    return '';
                }
            },
            'format' => 'raw',
        ]*/
                ],
            ]); ?>
        </div>
    </div>
</div>

<?php \yii\widgets\Pjax::end() ?>

