<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
 * @var yii\web\View $this
 * @var backend\models\PerusahaanSatu $model
 */

$this->title = 'Perusahaan : ' . $model->nama_perusahaan;
$this->params['breadcrumbs'][] = ['label' => 'Perusahaan Satu', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->nama_perusahaan, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('cruds', 'View');
?>
<div class="giiant-crud perusahaan-satu-view">

    <!-- menu buttons -->
    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('cruds', 'Edit'), ['update', 'id' => $model->id], ['class' => 'btn btn-info']) ?>
    </p>

    <p class="pull-right">
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . Yii::t('cruds', 'Daftar Perusahaan Satu'), ['index'], ['class' => 'btn btn-default']) ?>
    </p>

    <div class="clearfix"></div>

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <div class="box box-info">
        <div class="box-body">
            <?php $this->beginBlock('backend\models\PerusahaanSatu'); ?>

            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
//                    'id',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
                    [
                        'format' => 'html',
                        'attribute' => 'id_usaha',
                        'value' => ($model->getIdUsaha()->one() ?
                            $model->getIdUsaha()->one()->nama_usaha
                            :
                            '<span class="label label-warning">?</span>'),
                    ],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
                    [
                        'format' => 'html',
                        'attribute' => 'id_bisnis',
                        'value' => ($model->getIdBisnis()->one() ?
                            $model->getIdBisnis()->one()->nama_tahapan_bisnis
                            :
                            '<span class="label label-warning">?</span>'),
                    ],
                    'nama_perusahaan',
                    [
                        'format' => 'html',
                        'attribute' => 'logo_perusahaan',
                        'value' => '<img width="150px" height="150px" src="../uploads/perusahaan_st/' . $model->logo_perusahaan . '"></span>'

                    ],
                    'tahun_berdiri',
                    'alamat_perusahaan',
                    'no_telp_kantor',
                    'email_kantor:email',
                    'deskripsi_singkat:ntext',
                    'deskripsi_panjang:ntext',
                    [
                        'format' => 'html',
                        'attribute' => 'portofolio_perusahaan',
                        'value' => '<img width="150px" height="150px" src="../uploads/perusahaan_st/' . $model->portofolio_perusahaan . '"></span>'

                    ],
                    [
                        'format' => 'html',
                        'attribute' => 'foto_dokumentasi',
                        'value' => '<img width="150px" height="150px" src="../uploads/perusahaan_st/' . $model->foto_dokumentasi . '"></span>'

                    ],
                    [
                        'format' => 'html',
                        'attribute' => 'upload_company_profile',
                        'value' => '<a href="' . Yii::$app->request->baseUrl . '/uploads/perusahaan_st/'.$model->upload_company_profile.'">Download</a>'

                    ],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
//                    [
//                        'format' => 'html',
//                        'attribute' => 'id_user',
//                        'value' => ($model->getIdUser()->one() ?
//                            Html::a('<i class="glyphicon glyphicon-list"></i>', ['user/index']) . ' ' .
//                            Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> ' . $model->getIdUser()->one()->id, ['user/view', 'id' => $model->getIdUser()->one()->id,]) . ' ' .
//                            Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'PerusahaanSatu' => ['id_user' => $model->id_user]])
//                            :
//                            '<span class="label label-warning">?</span>'),
//                    ],
                ],
            ]); ?>

            <hr/>

            <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('cruds', 'Delete'), ['delete', 'id' => $model->id],
                [
                    'class' => 'btn btn-danger',
                    'data-confirm' => '' . Yii::t('cruds', 'Are you sure to delete this item?') . '',
                    'data-method' => 'post',
                ]); ?>
            <?php $this->endBlock(); ?>



            <?= Tabs::widget(
                [
                    'id' => 'relation-tabs',
                    'encodeLabels' => false,
                    'items' => [[
                        'label' => '<b class=""># ' . $model->nama_perusahaan . '</b>',
                        'content' => $this->blocks['backend\models\PerusahaanSatu'],
                        'active' => true,
                    ],]
                ]
            );
            ?>
        </div>
    </div>
</div>
