<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "akademik".
 *
 * @property integer $id
 * @property double $nim
 * @property integer $jurusan
 * @property double $batch
 *
 * @property \backend\models\MasterJurusan $jurusan0
 * @property string $aliasModel
 */
abstract class Akademik extends \yii\db\ActiveRecord
{


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'akademik';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nim', 'jurusan', 'batch'], 'required'],
            [['nim', 'batch'], 'number'],
            [['jurusan'], 'integer'],
            [['jurusan'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\MasterJurusan::className(), 'targetAttribute' => ['jurusan' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nim' => 'Nim',
            'jurusan' => 'Jurusan',
            'batch' => 'Batch',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJurusan0()
    {
        return $this->hasOne(\backend\models\MasterJurusan::className(), ['id' => 'jurusan']);
    }


}
