<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "bisnis".
 *
 * @property integer $id
 * @property string $nama_tahapan_bisnis
 *
 * @property \backend\models\PerusahaanDua[] $perusahaanDuas
 * @property \backend\models\PerusahaanEmpat[] $perusahaanEmpats
 * @property \backend\models\PerusahaanSatu[] $perusahaanSatus
 * @property \backend\models\PerusahaanTiga[] $perusahaanTigas
 * @property string $aliasModel
 */
abstract class Bisnis extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bisnis';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama_tahapan_bisnis'], 'required'],
            [['nama_tahapan_bisnis'], 'string', 'max' => 250]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama_tahapan_bisnis' => 'Nama Tahapan Bisnis',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPerusahaanDuas()
    {
        return $this->hasMany(\backend\models\PerusahaanDua::className(), ['id_bisnis' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPerusahaanEmpats()
    {
        return $this->hasMany(\backend\models\PerusahaanEmpat::className(), ['id_bisnis' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPerusahaanSatuses()
    {
        return $this->hasMany(\backend\models\PerusahaanSatu::className(), ['id_bisnis' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPerusahaanTigas()
    {
        return $this->hasMany(\backend\models\PerusahaanTiga::className(), ['id_bisnis' => 'id']);
    }




}
