<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "data_diri".
 *
 * @property integer $id
 * @property integer $id_user
 * @property string $nama_lengkap
 * @property string $nama_panggilan
 * @property string $foto
 * @property string $tempat_lahir
 * @property string $alamat_tinggal
 * @property double $no_hp
 * @property string $email
 * @property string $akun_fb
 * @property string $akun_ig
 * @property string $akun_li
 *
 * @property \backend\models\User $idUser
 * @property string $aliasModel
 */
abstract class DataDiri extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'data_diri';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            //[['id_user', 'nama_lengkap', 'nama_panggilan', 'foto', 'tempat_lahir', 'alamat_tinggal', 'no_hp', 'email'], 'required'],
            [['id_user'], 'integer'],
            [['no_hp'], 'number'],
            [['nama_lengkap', 'foto', 'alamat_tinggal'], 'string', 'max' => 250],
            [['nama_panggilan', 'akun_fb', 'akun_ig', 'akun_li'], 'string', 'max' => 100],
            [['tempat_lahir', 'email'], 'string', 'max' => 150],
            [['id_user'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\User::className(), 'targetAttribute' => ['id_user' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_user' => 'User',
            'nama_lengkap' => 'Nama Lengkap',
            'nama_panggilan' => 'Nama Panggilan',
            'foto' => 'Foto',
            'tempat_lahir' => 'Tempat Lahir',
            'alamat_tinggal' => 'Alamat Tinggal',
            'no_hp' => 'No Hp',
            'email' => 'E-mail',
            'akun_fb' => 'Akun Facebook',
            'akun_ig' => 'Akun Instagram',
            'akun_li' => 'Akun Linkedin',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdUser()
    {
        return $this->hasOne(\backend\models\User::className(), ['id' => 'id_user']);
    }




}
