<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "perusahaan_satu".
 *
 * @property integer $id
 * @property integer $id_usaha
 * @property integer $id_bisnis
 * @property string $nama_perusahaan
 * @property string $logo_perusahaan
 * @property integer $tahun_berdiri
 * @property string $alamat_perusahaan
 * @property double $no_telp_kantor
 * @property string $email_kantor
 * @property string $deskripsi_singkat
 * @property string $deskripsi_panjang
 * @property string $portofolio_perusahaan
 * @property string $foto_dokumentasi
 * @property string $upload_company_profile
 * @property integer $id_user
 *
 * @property \backend\models\Usaha $idUsaha
 * @property \backend\models\Bisnis $idBisnis
 * @property \backend\models\User $idUser
 * @property string $aliasModel
 */
abstract class PerusahaanSatu extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'perusahaan_satu';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_usaha', 'id_bisnis', 'nama_perusahaan', 'tahun_berdiri', 'alamat_perusahaan', 'no_telp_kantor', 'email_kantor', 'deskripsi_singkat', 'deskripsi_panjang', 'id_user'], 'required'],
            [['id_usaha', 'id_bisnis', 'tahun_berdiri', 'id_user'], 'integer'],
            [['no_telp_kantor'], 'number'],
            [['deskripsi_singkat', 'deskripsi_panjang'], 'string'],
            [['nama_perusahaan', 'email_kantor'], 'string', 'max' => 150],
            [['logo_perusahaan', 'alamat_perusahaan', 'portofolio_perusahaan', 'foto_dokumentasi', 'upload_company_profile'], 'string', 'max' => 250],
            [['id_usaha'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\Usaha::className(), 'targetAttribute' => ['id_usaha' => 'id']],
            [['id_bisnis'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\Bisnis::className(), 'targetAttribute' => ['id_bisnis' => 'id']],
            [['id_user'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\User::className(), 'targetAttribute' => ['id_user' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_usaha' => 'Usaha',
            'id_bisnis' => 'Bisnis',
            'nama_perusahaan' => 'Nama Perusahaan',
            'logo_perusahaan' => 'Logo Perusahaan',
            'tahun_berdiri' => 'Tahun Berdiri',
            'alamat_perusahaan' => 'Alamat Perusahaan',
            'no_telp_kantor' => 'No Telp Kantor',
            'email_kantor' => 'E-Mail Kantor',
            'deskripsi_singkat' => 'Deskripsi Singkat',
            'deskripsi_panjang' => 'Deskripsi Panjang',
            'portofolio_perusahaan' => 'Portofolio Perusahaan',
            'foto_dokumentasi' => 'Foto Dokumentasi',
            'upload_company_profile' => 'Upload Company Profile',
            'id_user' => 'User',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdUsaha()
    {
        return $this->hasOne(\backend\models\Usaha::className(), ['id' => 'id_usaha']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdBisnis()
    {
        return $this->hasOne(\backend\models\Bisnis::className(), ['id' => 'id_bisnis']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdUser()
    {
        return $this->hasOne(\backend\models\User::className(), ['id' => 'id_user']);
    }




}
