<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "project_progress".
 *
 * @property integer $id
 * @property integer $id_project
 * @property string $gambar
 *
 * @property \backend\models\Project $idProject
 * @property string $aliasModel
 */
abstract class ProjectProgress extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'project_progress';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_project'], 'required'],
            [['id_project'], 'integer'],
            [['gambar'], 'string', 'max' => 250],
            [['id_project'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\Project::className(), 'targetAttribute' => ['id_project' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_project' => 'Judul Project',
            'gambar' => 'Gambar',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdProject()
    {
        return $this->hasOne(\backend\models\Project::className(), ['id' => 'id_project']);
    }




}
