<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "tentang".
 *
 * @property integer $id
 * @property string $isi
 * @property string $aliasModel
 */
abstract class Tentang extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tentang';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['isi'], 'required'],
            [['isi'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'isi' => 'Isi',
        ];
    }




}
