<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "usaha".
 *
 * @property integer $id
 * @property string $nama_usaha
 *
 * @property \backend\models\PerusahaanSatu[] $perusahaanSatus
 * @property string $aliasModel
 */
abstract class Usaha extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'usaha';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama_usaha'], 'required'],
            [['nama_usaha'], 'string', 'max' => 250]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama_usaha' => 'Nama Usaha',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPerusahaanSatuses()
    {
        return $this->hasMany(\backend\models\PerusahaanSatu::className(), ['id_usaha' => 'id']);
    }




}
